### ISSUE TITLE
Load Agent Skills at Boot

### ISSUE THREAD

**Issue by geowa4** [585-software/medera#10]
Each Agent has many skills. When the Agent starts. it must load these skills definitions from a YAML configuration file. Each skill is a verb, noun, description, and a command. The verb-noun pair is what is entered in Slack (e.g. `list-homedirectory`), and the command is the executable with its arguments. See below for an example configuration file.

```
---
skills:
  - description: Lists files in a directory
    verb: list
    noun: homedirectory
    command: /bin/ls ~
```
